name: IPTV Otomatik Guncelleyici

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Kanalları Test Et ve Temizle
        run: python update_playlist.py

      - name: Yeni Calisan Listeyi Kaydet
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add canli_kanallar.m3u
          git commit -m "Otomatik Canlı Kanallar Güncellendi [skip ci]" || echo "Değişiklik yok"
          git push
